### ISSUE TITLE
combined delayed assert and Hamcrest assert

### ISSUE THREAD

**Issue by tbradley-sans** [pr4bh4sh/delayed-assert#13]
Does anyone know of any project that combine delayed-assert and the Python Hamcrest assert into a single class? I like the features of both and would like to use them together. That is, I would like to do something like this:

```
delayed_assert.assert_that(response.text, equal_to_ignoring_case("Error"))
delayed_assert.assert_that(response.time, close_to(42.0))
delayed_assert.assert_that(response, instance_of(Response))
delayed_assert.assert_expectations()
```

**Comment by pr4bh4sh** [comment]
Please try as [here](https://github.com/pr4bh4sh/delayed-assert/blob/10a8a6bbd889e6acaad0be14b20b24ac9f4349a3/ExampleUnittest.py#L15) and let me know if it does not works

```python
expect(lambda: assert_that(response.text, equal_to_ignoring_case("Error")
```

**Comment by tbradley-sans** [comment]
That's a great idea. I will try it when I have a chance, and report back. Thanks.

**Comment by tbradley-sans** [comment]
I tried that approach, and it seems to work fine for my case. Thank you.
