### ISSUE TITLE
how to instantiate a delayed assert

### ISSUE THREAD

**Issue by tbradley-sans** [pr4bh4sh/delayed-assert#14]
Hi, is there a way to instantiate a delayed assert, or in some other way have multiple assertions accumulating expectations at the same time? What I was imagining was the ability to do something like this, but with `da` being non-global.

```
da = some_function()
da.expect(2 == 4, "another checkpoint")
da.assert_expectations()

def some_function():
        delayed_assert = DelayedAssert()
        delayed_assert.expect(1 == 1, "checkpoint related to some_function")
        delayed_assert.expect(1 == 2, "another checkpoint related to some function")
        return delayed_assert
```

**Comment by vishuhanda** [comment]
Hi
Using delayed assert
1. it does not gives a concrete message upon exception when failed
![image](https://user-images.githubusercontent.com/49567970/117551815-b3396280-b065-11eb-8371-9c2ed21cd1ec.png)
2. You should remove the method name starts from "test". This is not needful
