### ISSUE TITLE
The old 0.3.2 version in pip

### ISSUE THREAD

**Issue by dmrlx** [pr4bh4sh/delayed-assert#19]
Hello,
Are you going to add the latest version of the lib to pip?

**Comment by pr4bh4sh** [comment]
Thanks for reminding, I completely forgot about it. I'll set a reminder and do it this weekend.

**Comment by pr4bh4sh** [comment]
@dmrlx version 0.3.3 and 0.3.4 is uploaded. https://pypi.org/project/delayed-assert/#history

**Comment by dmrlx** [comment]
@pr4bh4sh Thanks a lot!
