### ISSUE TITLE
delayed assert expect call is failing

### ISSUE THREAD

**Issue by Prasannajnaeyulu** [pr4bh4sh/delayed-assert#20]
**delayed_assert version 0.3.4**

from delayed_assert import expect
expect(actual_service_exitcode == int(expected_exitcode),
               "Expected exit code to be {}, but it was {}".format(context.modbus_client_expect_exitcode_is,
                                                                   context.modbus_client_exitcode))

Note: Here  expected_exitcode is: 124
actual_service_exitcode  is: 124

File "/usr/local/lib/python3.5/dist-packages/delayed_assert/delayed_assert.py", line 52, in expect
           raise Exception("Could not identify test method, make sure the call for 'expect' method is originated with 'test' method")
       Exception: Could not identify test method, make sure the call for 'expect' method is originated with 'test' method

**Actual:** I could see there is a new functionality added in this new version to make sure expect() method being called from within a function with name starts with test*. As my caller method name does not start with test*, it is failing with the above error which is expected as per the current implementation.

**Expected:** Why the method name should starts with test* I donot understand the rationale behind this (might be the expectation is this library is only been using by some unit test frameworks where they might enforce the method names should starts with test* like pytest etc..). But, I am using a behave framework for my functional tests automation and I am using this library to perform assertions as part of validation and the method name from which I am calling expect() is arbitrary; It can be anything not necessiarly starts with test*.

**Comment by iivanou** [comment]
Is reproducible with 2.7 as well.

**Comment by Prasannajnaeyulu** [comment]
@iivanou it’s not about python version. It is the latest version 0.3.4 of delayed-assert library that’s causing the problem as they introduced a breaking change in this release. I would advise you to please use 0.3.2 version to keep away from this breaking change. The authors wrongly understood that this library is only been using by people along with unit test frameworks Like pytest .

**Comment by Prasannajnaeyulu** [comment]
Do this to install previous version 
‘pip install delayed-assert=0.3.2‘
